### ISSUE TITLE
first tryout, can't start Gush server

### ISSUE THREAD

**Issue by andrea-spoldi** [chaps-io/gush#11]
Hi,
 I'm trying Gush out for the first time, followed the Readme but either with Rails app or simple Ruby I got this message when running "bundle exec gush workers"

/var/lib/gems/2.0.0/gems/gush-0.1.1/lib/gush/cli.rb:134:in `load_gushfile': undefined method `exist?' for nil:NilClass (NoMethodError)

my Gushfile.rb is in the root of my project, even though with Rails app it shouldn't be necessary as stated in Readme

trying with a non Rails app my Gushfile looks like this : 

```ruby
require 'gush'

Dir["#{File.dirname(__FILE__)}/app/workflows/**/*.rb"].each { |f| puts f; require f }
Dir["#{File.dirname(__FILE__)}/app/jobs/**/*.rb"].each { |f| puts f; require f }
```

but still same error
any ideas anyone ? 

I'm using ruby 2.0.0p384 (2014-01-12) [x86_64-linux-gnu]

ty

**Comment by pokonski** [comment]
Hi Andrea,

sorry about the confusion in Readme. Gush is not yet autoloading files when in Rails app. 

That said I fixed your bug in 0.1.2 which I just pushed to Rubygems. Can you try it now?

**Comment by andrea-spoldi** [comment]
Hi @pokonski  thanks for prompt reply
I did updated my bundle, now that error is gone but I still cannot run it : 

/usr/lib/ruby/2.0.0/pathname.rb:389:in `initialize': no implicit conversion of nil into String (TypeError)
	from /usr/lib/ruby/2.0.0/pathname.rb:389:in `new'
	from /usr/lib/ruby/2.0.0/pathname.rb:389:in `join'
	from /var/lib/gems/2.0.0/gems/gush-0.1.2/lib/gush/cli.rb:129:in `gushfile'
	from /var/lib/gems/2.0.0/gems/gush-0.1.2/lib/gush/cli.rb:134:in `load_gushfile'
	from /var/lib/gems/2.0.0/gems/gush-0.1.2/lib/gush/cli.rb:25:in `initialize'
	from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:355:in `new'
	from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:355:in `dispatch'
	from /var/lib/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.0.0/gems/gush-0.1.2/bin/gush:13:in `<top (required)>'
	from /usr/local/bin/gush:23:in `load'
	from /usr/local/bin/gush:23:in `<main>'

didn't change my Gushfile, error's the same with or without Rails

ty

A

**Comment by pokonski** [comment]
Thanks for the stacktrace, I will inspect on my existing projects and try to recreate it. Then get back to you :)

**Comment by andrea-spoldi** [comment]
@pokonski I think I've managed to move on...
had to specify "-f <path to gushfile.rb>" 

so it becomes : 
bundle exec gush workers -f ./Gushfile.rb 

I got other errors there but I think I can manage it...
I suppose Readme should be slightly improved ;)

**Comment by jalberto** [comment]
Whats the recommended way to run Gush in a Rails (api) project?

I'm trying:

```
APP_PATH = File.expand_path('./config/application', __FILE__)
require_relative './config/boot'
require_relative './config/application'

Dir[Rails.root.join("app/workflows/**/*.rb")].each do |file|
  require file
end
Dir[Rails.root.join("app/jobs/**/*.rb")].each do |file|
  require file
end
```

But is not working properly, every job just faill on start (but works as regular sidekiq worker)
